// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwtcnnqmduyjbnglsqxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3dGNubnFtZHV5amJuZ2xzcXhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NjQ4NzksImV4cCI6MjA2NzA0MDg3OX0.BMx1Lpo5qXaMYrk7z86p7NRFHcxuupxTP0iHuTLakiA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});